import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "react-bootstrap";
import Navbar from "@/components/Navbar/Navbar";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Sidebar />
        <div className={styles.content_area}>
          <div className={styles.circle}></div>
          <div className={styles.container_fluid_custom}>
            <div className="row">
              <div className="col-12">
                <div className={styles.panelbox}>ハブ管理ページ</div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
